server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  socket:
    host: 0.0.0.0
    port: 9092
    allowedOrigins: "*"
  redis:
    url: redis://127.0.0.1:6379